fix(deps): update dependency axios to v1.7.7 (#1105)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [axios](https://axios-http.com)
([source](https://redirect.github.com/axios/axios)) | [`1.7.2` ->
`1.7.7`](https://renovatebot.com/diffs/npm/axios/1.7.2/1.7.7) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/axios/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/axios/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/axios/1.7.2/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/axios/1.7.2/1.7.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>axios/axios (axios)</summary>

###
[`v1.7.7`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#177-2024-08-31)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.6...v1.7.7)

##### Bug Fixes

- **fetch:** fix stream handling in Safari by fallback to using a stream
reader instead of an async iterator;
([#&#8203;6584](https://redirect.github.com/axios/axios/issues/6584))
([d198085](https://redirect.github.com/axios/axios/commit/d1980854fee1765cd02fa0787adf5d6e34dd9dcf))
- **http:** fixed support for IPv6 literal strings in url
([#&#8203;5731](https://redirect.github.com/axios/axios/issues/5731))
([364993f](https://redirect.github.com/axios/axios/commit/364993f0d8bc6e0e06f76b8a35d2d0a35cab054c))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/10539109?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/>
[Rishi556](https://redirect.github.com/Rishi556 "+39/-1 (#&#8203;5731
)")
- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+27/-7
(#&#8203;6584 )")

###
[`v1.7.6`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#176-2024-08-30)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.5...v1.7.6)

##### Bug Fixes

- **fetch:** fix content length calculation for FormData payload;
([#&#8203;6524](https://redirect.github.com/axios/axios/issues/6524))
([085f568](https://redirect.github.com/axios/axios/commit/085f56861a83e9ac02c140ad9d68dac540dfeeaa))
- **fetch:** optimize signals composing logic;
([#&#8203;6582](https://redirect.github.com/axios/axios/issues/6582))
([df9889b](https://redirect.github.com/axios/axios/commit/df9889b83c2cc37e9e6189675a73ab70c60f031f))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+98/-46
(#&#8203;6582 )")
- <img
src="https://avatars.githubusercontent.com/u/3534453?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Jacques
Germishuys](https://redirect.github.com/jacquesg "+5/-1 (#&#8203;6524
)")
- <img
src="https://avatars.githubusercontent.com/u/53894505?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/>
[kuroino721](https://redirect.github.com/kuroino721 "+3/-1 (#&#8203;6575
)")

###
[`v1.7.5`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#175-2024-08-23)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.4...v1.7.5)

##### Bug Fixes

- **adapter:** fix undefined reference to hasBrowserEnv
([#&#8203;6572](https://redirect.github.com/axios/axios/issues/6572))
([7004707](https://redirect.github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1))
- **core:** add the missed implementation of AxiosError#status property;
([#&#8203;6573](https://redirect.github.com/axios/axios/issues/6573))
([6700a8a](https://redirect.github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852))
- **core:** fix `ReferenceError: navigator is not defined` for custom
environments;
([#&#8203;6567](https://redirect.github.com/axios/axios/issues/6567))
([fed1a4b](https://redirect.github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794))
- **fetch:** fix credentials handling in Cloudflare workers
([#&#8203;6533](https://redirect.github.com/axios/axios/issues/6533))
([550d885](https://redirect.github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+187/-83
(#&#8203;6573 #&#8203;6567 #&#8203;6566 #&#8203;6564 #&#8203;6563
#&#8203;6557 #&#8203;6556 #&#8203;6555 #&#8203;6554 #&#8203;6552 )")
- <img
src="https://avatars.githubusercontent.com/u/2495809?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Antonin
Bas](https://redirect.github.com/antoninbas "+6/-6 (#&#8203;6572 )")
- <img
src="https://avatars.githubusercontent.com/u/5406212?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Hans Otto
Wirtz](https://redirect.github.com/hansottowirtz "+4/-1 (#&#8203;6533
)")

###
[`v1.7.4`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#174-2024-08-13)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.3...v1.7.4)

##### Bug Fixes

- **sec:** CVE-2024-39338
([#&#8203;6539](https://redirect.github.com/axios/axios/issues/6539))
([#&#8203;6543](https://redirect.github.com/axios/axios/issues/6543))
([6b6b605](https://redirect.github.com/axios/axios/commit/6b6b605eaf73852fb2dae033f1e786155959de3a))
- **sec:** disregard protocol-relative URL to remediate SSRF
([#&#8203;6539](https://redirect.github.com/axios/axios/issues/6539))
([07a661a](https://redirect.github.com/axios/axios/commit/07a661a2a6b9092c4aa640dcc7f724ec5e65bdda))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/31389480?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Lev
Pachmanov](https://redirect.github.com/levpachmanov "+47/-11
(#&#8203;6543 )")
- <img
src="https://avatars.githubusercontent.com/u/41283691?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Đỗ Trọng
Hải](https://redirect.github.com/hainenber "+49/-4 (#&#8203;6539 )")

###
[`v1.7.3`](https://redirect.github.com/axios/axios/blob/HEAD/CHANGELOG.md#173-2024-08-01)

[Compare
Source](https://redirect.github.com/axios/axios/compare/v1.7.2...v1.7.3)

##### Bug Fixes

- **adapter:** fix progress event emitting;
([#&#8203;6518](https://redirect.github.com/axios/axios/issues/6518))
([e3c76fc](https://redirect.github.com/axios/axios/commit/e3c76fc9bdd03aa4d98afaf211df943e2031453f))
- **fetch:** fix withCredentials request config
([#&#8203;6505](https://redirect.github.com/axios/axios/issues/6505))
([85d4d0e](https://redirect.github.com/axios/axios/commit/85d4d0ea0aae91082f04e303dec46510d1b4e787))
- **xhr:** return original config on errors from XHR adapter
([#&#8203;6515](https://redirect.github.com/axios/axios/issues/6515))
([8966ee7](https://redirect.github.com/axios/axios/commit/8966ee7ea62ecbd6cfb39a905939bcdab5cf6388))

##### Contributors to this release

- <img
src="https://avatars.githubusercontent.com/u/12586868?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Dmitriy
Mozgovoy](https://redirect.github.com/DigitalBrainJS "+211/-159
(#&#8203;6518 #&#8203;6519 )")
- <img
src="https://avatars.githubusercontent.com/u/10867286?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [Valerii
Sidorenko](https://redirect.github.com/ValeraS "+3/-3 (#&#8203;6515 )")
- <img
src="https://avatars.githubusercontent.com/u/8599535?v&#x3D;4&amp;s&#x3D;18"
alt="avatar" width="18"/> [prianYu](https://redirect.github.com/prianyu
"+2/-2 (#&#8203;6505 )")

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "every weekday" in timezone Etc/UTC,
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/ScaleLeap/selling-partner-api-sdk).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOC43NC4xIiwidXBkYXRlZEluVmVyIjoiMzguNzQuMSIsInRhcmdldEJyYW5jaCI6Im1hc3RlciIsImxhYmVscyI6WyJyZW5vdmF0ZWJvdCJdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>